# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('scheduledDate', models.DateField()),
                ('scheduledTime', models.DateTimeField()),
                ('notes', models.TextField()),
                ('checkinTime', models.DateTimeField()),
                ('checkoutTime', models.DateTimeField()),
                ('appointmentStart', models.DateTimeField()),
                ('appointmentEnd', models.DateTimeField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('diagnosesID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('diagnosesName', models.TextField()),
                ('diagnosesDateBegin', models.DateTimeField()),
                ('diagnosesDateEND', models.DateTimeField()),
                ('diagnosesSeverity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('noteID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('noteText', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('middleI', models.CharField(max_length=1, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('fileKey', models.CharField(max_length=30, null=True)),
                ('maritalStat', models.CharField(max_length=30, null=True)),
                ('phone', models.PositiveIntegerField(null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mailingAdd', models.CharField(max_length=250)),
                ('children', models.PositiveIntegerField()),
                ('medicalHistory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescriptionID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('prescriptionTxt', models.TextField()),
                ('printTime', models.DateTimeField()),
                ('createdTime', models.DateTimeField()),
                ('prescriptionTitle', models.CharField(max_length=250)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dayOfWeek', models.DateField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.Patient'),
        ),
    ]
