# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_auto_20170424_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnoses',
            name='diagnosesID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='noteID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescriptionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='scheduleID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
