# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0003_auto_20170424_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='dayOfWeek',
            field=models.CharField(max_length=30),
        ),
    ]
